version: "3"

# 정의할 서비스들의 목록
services:  
  # 서비스 이름 지정
  frontend:  
    # 컨테이너 이름 지정 (선택 사항)
    container_name: react-container
    # command: npm start
    # 이미지 빌드 설정
    build:  
      context: .  # Dockerfile을 빌드하는 기준 경로 (현재 디렉토리)
      dockerfile: ./Dockerfile  # 사용할 Dockerfile의 경로
    # 포트 매핑 (호스트 포트:컨테이너 포트)
    ports:  
      - "3000:3000"  # 호스트의 3000 포트와 컨테이너의 3000 포트를 매핑
    # # 컨테이너 재시작 정책 (항상 재시작)
    # depends_on:
    #   - mosquitto
    # networks:
    #   - eclipse-mosquitto-A101-network
    networks:
      - A101-network
    restart: always
  mosquitto:
    image: "eclipse-mosquitto"
    container_name: mqtt-container
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /var/jenkins_home/workspace/A101/frontend/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /var/jenkins_home/workspace/A101/frontend/mqtt/data:/mosquitto/data
      - /var/jenkins_home/workspace/A101/frontend/mqtt/log:/mosquitto/log
    networks:
      - A101-network
    restart: always
networks:
  A101-network:
    driver: bridge
