version: "3"
services:
  spring:
    # 컨테이너 이름
    container_name: spring-container
    build:
      # 경로
      context: .
      # 사용할(?) docker 파일
      dockerfile: ./Dockerfile
    ports:
      # 지정 포트
      # 호스트의 8080 포트를 컨테이너의 8080 포트와 매핑
      - 8000:8000
    volumes:
      # - /home/ubuntu/compose/jenkins/workspace/spring-boot-ci-cd/build/libs:/deploy
      # - /jenkins/workspace/A101/backend/build/libs:/deploy
      - /var/jenkins_home/workspace/A101/backend/build/libs:/deploy